spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.129.252.208:8863/erp_sys?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
    username: user_erp_sys
    password: Gt4fshDerGDfTr6723i
server:
  port: 8080
logging:
  level:
    com.xie.mapper: debug

rocketmq:
  name-server: 192.168.20.211:9876
  producer:
    group: wxProducerGroup


